


---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "nginx-deployment"
  namespace: "default"
  labels:
    app: "nginx-deployment"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "nginx-deployment"
  template:
    metadata:
      labels:
        app: "nginx-deployment"
        version: "1.1.0"        
    spec:
      containers:
      - name: "nginx-deployment"
        #image: "nginx:1.23.3"
        image: "gcr.io/sincere-actor-377315/nginx-deployment:1.1.0"
        #image: "gcr.io/sincere-actor-377315/gcr-app-blue:latest"

---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "nginx-service"
  namespace: "default"
  labels:
    app: "nginx"
spec:
  ports:
  - protocol: "TCP"
    port: 80
  selector:
    app: "nginx-deployment"
    version: "1.1.0"
  type: "LoadBalancer"
  loadBalancerIP: ""