


---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "nginx-deployment"
  namespace: "default"
  labels:
    app: "nginx-deployment"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "nginx-deployment"
  template:
    metadata:
      labels:
        app: "nginx-deployment"
        version: "1.1.1"        
    spec:
      containers:
      - name: "nginx-deployment"
        #image: "nginx:1.23.3"
        image: "gcr.io/sincere-actor-377315/nginx-deployment:1.1.0"
