---
  name: Build and Push Python Image to Google Cloud Platform - GCR - roles/artifactregistry.createOnPushRepoAdmin
  on:
    push:
      branches: [ main ]
  job:
    job_id:
      steps:
      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.SERVICE_ACCOUNT_KEY }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: 'Use gcloud CLI'
        run: 'gcloud info'
