name: Push to GCR GitHub Action
on: [push]
jobs:
  build-and-push-to-gcr:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    env:
      GOOGLE_CREDENTIALS: ${{ secrets.SERVICE_ACCOUNT_KEY }}
      IMAGE_NAME: gcr-app-blue
      PROJECT_ID: sincere-actor-377315      
    steps:
      - uses: actions/checkout@v3
      - name: Authenticate to Google Cloud
        id: auth

        uses: google-github-actions/auth@v0
        with:
          #workload_identity_provider: projects/123123123/locations/global/workloadIdentityPools/the-workload-pool/providers/the-provider
          workload_identity_provider: projects/sincere-actor-377315/locations/us/repositories/gcr.io
          service_account: github-actions2@sincere-actor-377315.iam.gserviceaccount.com
      
      - name: Build Docker Image
        run: docker build -t $IMAGE_NAME:latest .
  
      - name: Automatic Tagging of Releases
        id: increment-git-tag
        run: |
          bash ./scripts/git_update.sh -v major
  
      - name: Configure Docker Client
        run: |-
          gcloud auth configure-docker --quiet
          gcloud auth configure-docker us-docker.pkg.dev --quiet
  
      - name: Push Docker Image to Container Registry (GCR)
        env:
          GIT_TAG: ${{ steps.increment-git-tag.outputs.git-tag }}
        run: |-
          docker tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
          docker tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:$GIT_TAG
          docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
          docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:$GIT_TAG
  
      - name: Push Docker Image to Artifact Registry
        env:
          GIT_TAG: ${{ steps.increment-git-tag.outputs.git-tag }}
        run: |-
          docker tag $IMAGE_NAME:latest us-docker.pkg.dev/$PROJECT_ID/images/$IMAGE_NAME:latest
          docker tag $IMAGE_NAME:latest us-docker.pkg.dev/$PROJECT_ID/images/$IMAGE_NAME:$GIT_TAG
          docker push us-docker.pkg.dev/$PROJECT_ID/images/$IMAGE_NAME:latest
          docker push us-docker.pkg.dev/$PROJECT_ID/images/$IMAGE_NAME:$GIT_TAG
  
